/**
 * Team Fortress 2 Classified | https://store.steampowered.com/app/3545060
 */
const TFTeam TFTeam_Green       = view_as<TFTeam>(4);
const TFTeam TFTeam_Yellow      = view_as<TFTeam>(5);
const TFTeam TF2CTeam_Halloween = view_as<TFTeam>(7);

#define TF2C_COND_TRANQUILIZED          136
#define TF2C_COND_CIV_SPEED             137
#define TF2C_COND_AIRBLAST              138
#define TF2C_COND_ANCHOR_FALL_CHARGED   139
#define TF2C_COND_LAUNCHED              140
#define TF2C_COND_JUMPPAD_ASSIST        141
#define TF2C_COND_JUST_USED_JUMPPAD     142
#define TF2C_COND_CIV_DAMAGE            143
#define TF2C_COND_LAUNCHED_SELF         144
#define TF2C_COND_CIV_HEAL              145
#define TF2C_COND_CONCUSSION            146
#define TF2C_COND_MIRV_SLOW             147
#define TF2C_COND_RESIDUAL_HEAL         148
#define TF2C_COND_BRICK                 149

const TFCond TF2CCond_Tranquilized      = view_as<TFCond>(TF2C_COND_TRANQUILIZED);
const TFCond TF2CCond_CivSpeed          = view_as<TFCond>(TF2C_COND_CIV_SPEED);
const TFCond TF2CCond_Airblast          = view_as<TFCond>(TF2C_COND_AIRBLAST);
const TFCond TF2CCond_AnchorFallCharged = view_as<TFCond>(TF2C_COND_ANCHOR_FALL_CHARGED);
const TFCond TF2CCond_Launched          = view_as<TFCond>(TF2C_COND_LAUNCHED);
const TFCond TF2CCond_JumppadAssist     = view_as<TFCond>(TF2C_COND_JUMPPAD_ASSIST);
const TFCond TF2CCond_JustUsedJumppad   = view_as<TFCond>(TF2C_COND_JUST_USED_JUMPPAD);
const TFCond TF2CCond_CivDamage         = view_as<TFCond>(TF2C_COND_CIV_DAMAGE);
const TFCond TF2CCond_LaunchedSelf      = view_as<TFCond>(TF2C_COND_LAUNCHED_SELF);
const TFCond TF2CCond_CivHeal           = view_as<TFCond>(TF2C_COND_CIV_HEAL);
const TFCond TF2CCond_Concussion        = view_as<TFCond>(TF2C_COND_CONCUSSION);
const TFCond TF2CCond_MirvSlow          = view_as<TFCond>(TF2C_COND_MIRV_SLOW);
const TFCond TF2CCond_ResidualHeal      = view_as<TFCond>(TF2C_COND_RESIDUAL_HEAL);
const TFCond TF2CCond_Brick             = view_as<TFCond>(TF2C_COND_BRICK);